### ISSUE TITLE
payment platform for banking using stablecoin 

### ISSUE THREAD

**Issue by fredaspen1** [radynamics/DalliPay#1]
Hello,

We are working on a stablecoin project build on Hedera Hashgraph blockchain, backed 1 to 1 with african currency, allowing people to access crypto markets. 

To bring more utility on the stablecoin, WE also want to make it a huge way of payment for institutions and retails, so we need this stablecoin running on payment platform for banking system (a kind of software) comply with ISO20022 standard.

Can you build it?

Hope to read you soon.

Fred

**Comment by rsteimen** [comment]
Hello,

DalliPay currently only integrates XRPL but is open for other blockchains. Hedera Hashgraph should be implementable. I'm happy to add it to our wishlist and wait for more interest until we consider an implementation.

**Comment by fredaspen1** [comment]
How much for our services?

**Comment by rsteimen** [comment]
I can't give any educated estimation due too many uncertainties. It's unclear what you meant with "our services". Generally speaking, supporting a new blockchain is a matter of several months at least.

I suggest further clarifying by mail we already exchanged.

**Comment by fredaspen1** [comment]
I just want to know if you Can build a payment platform for financial instutions, using a stablecoin and comply with ISO20022 standard.
If yes, how much for the service ?

**Comment by rsteimen** [comment]
I sent you a mail response according to your request a few days ago with additional questions about your project to estimate the range of effort needed. I didn't get any response as of today. Without more information the range in a magnitude of several months as mentioned earlier seems appropriate.

Please note that this "Issues" section if meant for technical issues. Let's take any further administrative communication back to our already started e-mail correspondence. As your created issue here doesn't address a specific technical issue, I'm going to close this issue later.
